---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      customize:
        memory: 4096
      network: 
      - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[xen-orchestra::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
